name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE (onedir)
        run: |
          pyinstaller --onedir --windowed --icon="assets/ferdlworks.ico" --name="FerdlWorks" --add-data="assets/ferdlworks_theme.json;assets" --add-data="assets/splashscreen.jpg;assets" --add-data="assets/signaturesound.wav;assets" --add-data="assets/signaturesound.ogg;assets" --add-data="assets/ferdlworks.ico;." --hidden-import="PIL._tkinter_finder" --hidden-import="win32print" --hidden-import="packaging" --hidden-import="packaging.version" main.py

      - name: Download Inno Setup
        shell: pwsh
        run: |
          $url = "https://github.com/jrsoftware/issrc/releases/download/is-6_4_2/InnoSetup-6.4.2.exe"
          $out = "$env:RUNNER_TEMP\is.exe"
          Invoke-WebRequest -Uri $url -OutFile $out
          Start-Process -FilePath $out -ArgumentList "/VERYSILENT /SUPPRESSMSGBOXES /NORESTART /DIR=`"$env:ProgramFiles\Inno Setup 6`"" -Wait

      - name: Build Installer
        shell: pwsh
        run: |
          & "$env:ProgramFiles\Inno Setup 6\ISCC.exe" "installer\ferdlworks.iss"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: installer\FerdlWorks-Setup.exe
          generate_release_notes: true
